# Generated by Django 2.2.5 on 2022-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='ip_image',
            new_name='input_image',
        ),
    ]
